godpig/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('godbody.urls')),
    url(r'^projectpig/', include('projectpig.urls')),
    url(r'^godcmdb/', include('godcmdb.urls')),
    url(r'^godsupport/', include('godsupport.urls')),
    url(r'^admin/', admin.site.urls),
    # url(r'^customers/$',views.customers),
]

godcmdb/models.py
# _*_ coding:utf-8 _*_
from __future__ import unicode_literals
from django.db import models
from godbody.models import UserProfile


# Create your models here.


class Asset(models.Model):
    asset_type_choices = (('server',u'物理机'),
                          ('openstack',u'云虚拟机'),
                          ('switch',u'交换机'),
                          ('router',u'路由器'),
                          ('firewall',u'防火墙'),
                          ('storage',u'存储设备'),
                          ('NLB',u'负载均衡'),
                          ('wireless',u'无线AP'),
                          ('software',u'软件资产'),
                          ('others',u'其它类'),
                          )
    asset_type = models.CharField(choices=asset_type_choices,max_length=64,default='server',verbose_name=u'设备类型')
    name = models.CharField(u'设备名',max_length=64,unique=True,blank=True,null=True)
    sn = models.CharField(u'资产SN号',max_length=128,unique=True,blank=True,null=True)
    production_test_choices =(
        (1,u'生产'),
        (2,u'测试'),
    )
    production_test = models.IntegerField(verbose_name=u'生产／测试',choices=production_test_choices,default=1)
    model = models.CharField(u'机柜号',max_length=12,null=True,blank=True)
    model_position = models.CharField(u'机柜位置',max_length=12,null=True,blank=True)
    manufactory = models.ForeignKey('Manufactory',verbose_name=u'制造商',blank=True,null=True)
    os_type = models.ForeignKey('Software',verbose_name=u'系统类型',blank=True,null=True)
    cpu_info = models.ForeignKey('CPU',verbose_name=u'CPU信息')
    mem_info = models.ForeignKey('RAM',verbose_name=u'内存信息')
    disk_info = models.ForeignKey('Disk',verbose_name=u'磁盘信息')
    management_ip = models.GenericIPAddressField(u'管理IP',blank=True,null=True)
    ip1 = models.GenericIPAddressField(u"eth1",blank=True,null=True)
    ip2 = models.GenericIPAddressField(u"eth2",blank=True,null=True)
    ip3 = models.GenericIPAddressField(u"eth3",blank=True,null=True)
    ip4 = models.GenericIPAddressField(u"eth4",blank=True,null=True)
    raid_type = models.CharField(u'raid类型',max_length=512,blank=True,null=True)
    contract = models.ForeignKey('Contract',verbose_name=u'合同',null=True,blank=True)
    trade_data = models.DateField(u'购买时间',null=True,blank=True)
    expire_date = models.DateField(u'过保修期',null=True,blank=True)
    price = models.FloatField(u'价格',null=True,blank=True)
    business_unit = models.ForeignKey('BusinessUnit',verbose_name=u'所属项目',blank=True,null=True)
    admin = models.ForeignKey(UserProfile,verbose_name='管理员',blank=True,null=True)
    idc = models.ForeignKey('IDC',verbose_name=u'IDC机房',null=True,blank=True)
    memo = models.TextField(u'备注',null=True,blank=True)
    create_date = models.DateTimeField(blank=True,auto_now_add=True)
    update_date = models.DateTimeField(blank=True,auto_now=True)

    class meta:
        verbose_name = "资产总表"
        verbose_name_plural = "资产总表"
    def __str__(self):
        return 'id:%s name:%s' %(self.id,self.name)

class Server(models.Model):
    asset = models.ForeignKey('Asset')
    created_by_choices = (
        ('auto',u'自动'),
        ('manual','手动'),
        )
    created_by = models.CharField(choices=created_by_choices,max_length=32,default='manual',verbose_name=u'添加模式')
    hosted_on = models.ForeignKey('self',related_name='hosted_on_server',blank=True,null=True)
    business_unit = models.ForeignKey('BusinessUnit',verbose_name=u'所属项目',blank=True,null=True)
    cpu_info = models.ForeignKey('CPU',verbose_name=u'CPU信息')
    mem_info = models.ForeignKey('RAM',verbose_name=u'内存信息')
    disk_info = models.ForeignKey('Disk',verbose_name=u'磁盘信息')
    IPS = models.ForeignKey('NIC',verbose_name=u'网卡信息',blank=True,null=True)
    ips1 = models.GenericIPAddressField(u"eth1",blank=True,null=True)
    ips2 = models.GenericIPAddressField(u"eth2",blank=True,null=True)
    ips3 = models.GenericIPAddressField(u"eth3",blank=True,null=True)
    os_type = models.ForeignKey('Software',verbose_name=u'系统类型',blank=True,null=True)
    admin = models.ForeignKey(UserProfile,verbose_name='项目管理员',blank=True,null=True)

    # os_distribution = models.CharField(u'发型版本',max_length=64,blank=True,null=True)
    # os_release = models.CharField(u'操作系统版本',max_length=64,blank=True,null=True)

    create_date = models.DateTimeField(blank=True,auto_now_add=True)
    update_date = models.DateTimeField(blank=True,null=True)
    class Meta:
        verbose_name = '服务器'
        verbose_name_plural = '服务器'

    def __str__(self):
        return '%s SN:%s' %(self.asset.name,self.IPS)


class NetworkDevice(models.Model):
    vlan_ip = models.GenericIPAddressField(u'VlanIP',blank=True,null=True)
    intranet_ip = models.GenericIPAddressField(u'内网IP',blank=True,null=True)
    sn = models.CharField(u'SN号',max_length=128,unique=True)
    manufactory = models.CharField(u'制造商',max_length=64,blank=True,null=True)
    model = models.CharField(u'型号',max_length=128,null=True,blank=True)
    firmware = models.ForeignKey('Software',blank=True,null=True)
    port_num = models.SmallIntegerField(u'端口个数',null=True,blank=True)
    device_detail = models.TextField(u'设置详细配置',null=True,blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(blank=True,null=True)

    class Meta:
        verbose_name = '网络设备'
        verbose_name_plural = '网络设备'

class Software(models.Model):
    os_types_choice = (('linux','Linux'),
                       ('windows','Windows'),
                       ('network_firmware','Network Firmware'),
                       ('software','Software'),
                       )
    os_distribution_choices = (('windows','Windows'),
                               ('centos','CentOS'),
                               ('redhat','Redhat'),
                               ('esxi','ESXI')
                               )
    type = models.CharField(u'系统类型',choices=os_types_choice,default=u'Linux',max_length=128)
    distribution = models.CharField(u'类型',choices=os_distribution_choices,default=u'redhat',max_length=128)
    version = models.CharField(u'软件／系统版本',max_length=64)
    language_choices = (('cn',u'中文'),
                        ('en',u'英文')
                        )
    language = models.CharField(u'系统语言',choices=language_choices,max_length=128)

    class Meta:
        verbose_name = '软件／系统'
        verbose_name_plural = '软件／系统'

    def __str__(self):
        return self.version


class CPU(models.Model):
    cpu_model = models.CharField(u'CPU型号',max_length=128,blank=True,null=True)
    cpu_count = models.SmallIntegerField(u'物理CPU个数',blank=True,null=True)
    cpu_core_count = models.SmallIntegerField(u'CPU核数',blank=True,null=True)
    memo = models.TextField(u'备注',null=True,blank=True)
    creat_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(blank=True,null=True)
    class Meta:
        verbose_name = 'CPU部件'
        verbose_name_plural = 'CPU部件'
    def __str__(self):
        return ("%s,%s")%(self.cpu_model,self.cpu_core_count)

class RAM(models.Model):
    sn = models.CharField(u'SN号',max_length=128,blank=True,null=True)
    model = models.CharField(u'内存型号',max_length=128,blank=True,null=True)
    manufactory = models.CharField(u'制造商',max_length=64,blank=True,null=True)
    slot = models.CharField(u'插槽',max_length=64,blank=True,null=True)
    capacity = models.CharField(u'内存大小(GB)',max_length=64)
    memo = models.CharField(u'备注',max_length=128,blank=True,null=True)
    create_date = models.DateTimeField(blank=True,auto_now_add=True)
    update_date = models.DateTimeField(blank=True,null=True)
    def __str__(self):
        return '%s:%s:%s' %(self.manufactory,self.slot,self.capacity)
    class Meta:
        verbose_name = 'RAM'
        verbose_name_plural = 'RAM'
        #unique_together = ("asset","slot")
    auto_create_fields = ['sn','slot','model','capacity']

class Disk(models.Model):
    sn = models.CharField(u'SN号',max_length=128,blank=True,null=True)
    slot = models.CharField(u'插槽位',max_length=64,blank=True,null=True)
    manufactory = models.CharField(u'制造商',max_length=64,blank=True,null=True)
    model = models.CharField(u'磁盘型号',max_length=128,blank=True,null=True)
    capacity = models.FloatField(u'磁盘容量GB')
    disk_iface_choice = (('SATA','SATA'),
                         ('SAS','SAS'),
                         ('SCSI','SCSI'),
                         ('SSD','SSD'),
                         )
    iface_type = models.CharField(u'接口类型',max_length=64,choices=disk_iface_choice,default='SAS',blank=True,null=True)
    memo = models.TextField(u'备注',blank=True,null=True)
    create_date = models.DateTimeField(blank=True,auto_now_add=True)
    update_date = models.DateTimeField(blank=True,null=True)

    auto_create_fields = ['sn','slot','manufactory','model','capacity']
    class Meta:
        #unique_together = ("asset","slot")
        verbose_name = '硬盘'
        verbose_name_plural = '硬盘'
    def __str__(self):
        return 'solt:%s capacity:%s' %(self.slot,self.capacity)

class NIC(models.Model):
    name = models.CharField(u'网卡名',max_length=64,blank=True,null=True)
    sn = models.CharField(u'SN号',max_length=128,blank=True,null=True)
    model = models.CharField(u'网卡型号',max_length=128,blank=True,null=True)
    macaddress = models.CharField(u'MAC',max_length=64,blank=True,null=True)
    ipaddress = models.GenericIPAddressField(u'IP',blank=True,null=True)
    netmask = models.CharField(u'子网掩码',max_length=64,blank=True,null=True)
    gateway = models.CharField(u'网关',max_length=64,blank=True,null=True)
    bonding = models.CharField(u'bond',max_length=64,blank=True,null=True)
    memo = models.CharField(u'备注',max_length=128,blank=True,null=True)
    create_date = models.DateTimeField(blank=True,auto_now_add=True)
    update_date = models.DateTimeField(blank=True,null=True)

    def __str__(self):
        return '%s:%s' % (self.macaddress,self.ipaddress)
    class Meta:
        verbose_name = u'网卡'
        verbose_name_plural = u"网卡"

templates/cmdb/Server_cmdb.html
{% extends 'start/index.html' %}
<!--导入godcmdb/templatetags/custom_tags-->>
{% load custom_tags %}

{% block  page-title %}

    CMDB
{% endblock %}

{% block page-content %}

  <div class="row">
    <div class="col-lg-12">

        <!--Network Line Chart-->
        <!--===================================================-->
        <div class="panel">
            <div class="panel-heading">
                <!--搜索框-->
                <form role="form" method="post">{% csrf_token %}
                    <div class="searchbox">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search.." name="ipnmb">
                            <span class="input-group-btn">
                                <button class="text-muted" type="button"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </div>
                </form>


                <div class="panel-control">

                    <button id="demo-panel-network-refresh" data-toggle="panel-overlay" data-target="#demo-panel-network" class="btn"><i class="fa fa-rotate-right"></i></button>
                    <div class="btn-group">
                        <button class="dropdown-toggle btn" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-gear"></i></button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#"></a></li>
                            <li><a href="#">添加</a></li>
                            <li><a href="#">跟进</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </div>
                </div>
                <h3 class="panel-title">主机资产</h3>
            </div>



            <!--Chart information-->
            <div class="panel-body " style="position:relative;z-index:2">
                <div class="row">
                 <table id='host_status_list' class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <td>设备类型</td>
                            <td>设备名</td>
                            <td>机柜号</td>
                            <td>所属业务</td>
                            <td>系统类型</td>
                            <td>管理IP</td>
                            <td>管理员</td>
                            <td>服务器IP</td>
                            <td>CPU信息</td>
                            <td>内存信息(G)</td>
                            <td>磁盘信息(GB)</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for server_cmdb in server_cmdb_obj %}
                        <tr>
                            <td data-type="asset_type">{{ server_cmdb.asset.get_asset_type_display}}</td>
                            <td data-type="production_test">{{ server_cmdb.asset.get_production_test_display}}</td>
                            <td data-type="model">{{ server_cmdb.asset.model}}</td>
                            <td data-type="business_unit">{{ server_cmdb.business_unit.name }}</td>
                            <td data-type="os_type">{{ server_cmdb.os_type.distribution }}:{{ server_cmdb.os_type}}</td>
                            <td data-type="management_ip"><a href="{% url 'server_cmdb_list_info' %}?id={{ server_cmdb.id }}">{{ server_cmdb.asset.management_ip }}</a></td>
                            <td data-type="admin">{{ server_cmdb.admin }}</td>
                            <td data-type="IPS">{{ server_cmdb.IPS.ipaddress }}</td>
                            <td data-type="cpu_info">{{ server_cmdb.cpu_info.cpu_core_count }}</td>
                            <td data-type="mem_info">{{ server_cmdb.mem_info.capacity }}</td>
                            <td data-type="disk_info">{{ server_cmdb.disk_info.capacity }}</td>
                        </tr>
                      {% endfor %}
                    </tbody>
                 </table>
                </div>
            </div>
        <!--===================================================-->
        <!--End network line chart-->

        </div>

    </div>
  </div>
<!--===================================================-->
        <!--分页配置-->
     <div class="pagination">

        <nav>
            <ul class="pagination">
                {% if server_cmdb_obj.has_previous %}
                    <li class=""><a href="?page={{ server_cmdb_obj.previous_page_number }}" aria-label="Previous">&laquo;</a></li>
                {% endif %}
                    {% for page_num in server_cmdb_obj.paginator.page_range %}
                        {% guess_page server_cmdb_obj.number page_num %}
                    {% endfor %}
                {% if server_cmdb_obj.has_next %}
                    <li class=""><a href="?page={{ server_cmdb_obj.next_page_number }}" aria-label="Next">&raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}

templates/cmdb/asset_cmdb_list.html
{% extends 'start/index.html' %}
<!--导入godcmdb/templatetags/custom_tags-->>
{% load custom_tags %}

{% block  page-title %}

    CMDB
{% endblock %}

{% block page-content %}

  <div class="row">
    <div class="col-lg-12">

        <!--Network Line Chart-->
        <!--===================================================-->
        <div class="panel">
            <div class="panel-heading">
                <!--搜索框-->
                <form role="form" method="post">{% csrf_token %}
                    <div class="searchbox">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search.." name="ipnmb">
                            <span class="input-group-btn">
                                <button class="text-muted" type="button"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </div>
                </form>


                <div class="panel-control">

                    <button id="demo-panel-network-refresh" data-toggle="panel-overlay" data-target="#demo-panel-network" class="btn"><i class="fa fa-rotate-right"></i></button>
                    <div class="btn-group">
                        <button class="dropdown-toggle btn" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-gear"></i></button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#"></a></li>
                            <li><a href="#">添加</a></li>
                            <li><a href="#">跟进</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </div>
                </div>
                <h3 class="panel-title">主机资产</h3>
            </div>



            <!--Chart information-->
            <div class="panel-body " style="position:relative;z-index:2">
                <div class="row">
                 <table id='host_status_list' class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <td>设备类型</td>
                            <td>生产／测试</td>
                            <td>机柜号</td>
                            <td>所属业务</td>
                            <td>系统类型</td>
                            <td>管理IP</td>
                            <td>管理员</td>
                            <td>服务器IP</td>
                            <td>CPU信息</td>
                            <td>内存信息(G)</td>
                            <td>磁盘信息(GB)</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for server_cmdb in server_cmdb_obj %}
                        <tr>
                            <td data-type="asset_type">{{ server_cmdb.asset.get_asset_type_display}}</td>
                            <td data-type="production_test">{{ server_cmdb.asset.get_production_test_display}}</td>
                            <td data-type="model">{{ server_cmdb.asset.model}}</td>
                            <td data-type="business_unit">{{ server_cmdb.business_unit.name }}</td>
                            <td data-type="os_type">{{ server_cmdb.os_type.distribution }}:{{ server_cmdb.os_type}}</td>
                            <td data-type="management_ip"><a href="{% url 'server_cmdb_list_info' %}?id={{ server_cmdb.id }}">{{ server_cmdb.asset.management_ip }}</a></td>
                            <td data-type="admin">{{ server_cmdb.admin }}</td>
                            <td data-type="IPS">{{ server_cmdb.IPS.ipaddress }}</td>
                            <td data-type="cpu_info">{{ server_cmdb.cpu_info.cpu_core_count }}</td>
                            <td data-type="mem_info">{{ server_cmdb.mem_info.capacity }}</td>
                            <td data-type="disk_info">{{ server_cmdb.disk_info.capacity }}</td>
                        </tr>
                      {% endfor %}
                    </tbody>
                 </table>
                </div>
            </div>
        <!--===================================================-->
        <!--End network line chart-->

        </div>

    </div>
  </div>
<!--===================================================-->
        <!--分页配置-->
     <div class="pagination">

        <nav>
            <ul class="pagination">
                {% if server_cmdb_obj.has_previous %}
                    <li class=""><a href="?page={{ server_cmdb_obj.previous_page_number }}" aria-label="Previous">&laquo;</a></li>
                {% endif %}
                    {% for page_num in server_cmdb_obj.paginator.page_range %}
                        {% guess_page server_cmdb_obj.number page_num %}
                    {% endfor %}
                {% if server_cmdb_obj.has_next %}
                    <li class=""><a href="?page={{ server_cmdb_obj.next_page_number }}" aria-label="Next">&raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}

templates/cmdb/search.html
{% extends 'start/index.html' %}
<!--导入godcmdb/templatetags/custom_tags-->>
{% load custom_tags %}

{% block  page-title %}

    CMDB
{% endblock %}

{% block page-content %}

  <div class="row">
    <div class="col-lg-12">

        <!--Network Line Chart-->
        <!--===================================================-->
        <div class="panel">
            <div class="panel-heading">
                <!--返回按钮-->
                <!--
                <div class="panel-control">
                    <div class="btn-group">
                        <button class="dropdown-toggle btn" data-toggle="dropdown" aria-expanded="false"><i class="glyphicon glyphicon-circle-arrow-left"></i>返回</button>
                    </div>
                </div>
                -->
                <h3 class="panel-title">{{ ips }}查询列表</h3>
            </div>



            <!--Chart information-->
            <div class="panel-body " style="position:relative;z-index:2">
                <div class="row">
                 <table id='host_status_list' class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <td>设备类型</td>
                            <td>生产／测试</td>
                            <td>机柜号</td>
                            <td>所属业务</td>
                            <td>系统类型</td>
                            <td>管理IP</td>
                            <td>管理员</td>
                            <td>服务器IP</td>
                            <td>CPU信息</td>
                            <td>内存信息(G)</td>
                            <td>磁盘信息(GB)</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for server_cmdb in server_cmdb_obj %}
                        <tr>
                            <td data-type="asset_type">{{ server_cmdb.asset.get_asset_type_display}}</td>
                            <td data-type="production_test">{{ server_cmdb.asset.get_production_test_display}}</td>
                            <td data-type="model">{{ server_cmdb.asset.model}}</td>
                            <td data-type="business_unit">{{ server_cmdb.business_unit.name }}</td>
                            <td data-type="os_type">{{ server_cmdb.os_type.distribution }}:{{ server_cmdb.os_type}}</td>
                            <td data-type="management_ip"><a href="{% url 'server_cmdb_list_info' %}?id={{ server_cmdb.id }}">{{ server_cmdb.asset.management_ip }}</a></td>
                            <td data-type="admin">{{ server_cmdb.admin }}</td>
                            <td data-type="IPS">{{ server_cmdb.IPS.ipaddress }}</td>
                            <td data-type="cpu_info">{{ server_cmdb.cpu_info.cpu_core_count }}</td>
                            <td data-type="mem_info">{{ server_cmdb.mem_info.capacity }}</td>
                            <td data-type="disk_info">{{ server_cmdb.disk_info.capacity }}</td>
                        </tr>
                      {% endfor %}
                    </tbody>
                 </table>
                </div>
            </div>
        <!--===================================================-->
        <!--End network line chart-->
            <div class="panel-control">

                <button id="demo-panel-network-refresh" data-toggle="panel-overlay" data-target="#demo-panel-network" class="btn"><i class="fa"></i>{{ SearchStatus }}</button>
                <div class="btn-group">
                    <button class="dropdown-toggle btn" data-toggle="dropdown" aria-expanded="false"><i class="fa "></i>查询条数：{{ ResultAmount }}</button>
                </div>
            </div>
        </div>

    </div>
  </div>
<!--===================================================-->
        <!--分页配置-->
     <div class="pagination">

        <nav>
            <ul class="pagination">
                {% if server_cmdb_obj.has_previous %}
                    <li class=""><a href="?page={{ server_cmdb_obj.previous_page_number }}" aria-label="Previous">&laquo;</a></li>
                {% endif %}
                    {% for page_num in server_cmdb_obj.paginator.page_range %}
                        {% guess_page server_cmdb_obj.number page_num %}
                    {% endfor %}
                {% if server_cmdb_obj.has_next %}
                    <li class=""><a href="?page={{ server_cmdb_obj.next_page_number }}" aria-label="Next">&raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}

templates/cmdb/server_cmdb_list_info.html
{% extends 'start/index.html' %}

{% block  page-title %}

    CMDB
{% endblock %}

{% block page-content %}

  <div class="row">
    <div class="col-lg-12">

        <!--Network Line Chart-->
        <!--===================================================-->
        <div class="panel">
            <div class="panel-heading">
                <div class="panel-control">
                    <button id="demo-panel-network-refresh" data-toggle="panel-overlay" data-target="#demo-panel-network" class="btn"><i class="fa fa-rotate-right"></i></button>
                </div>
                {% for name in godcmdb_record %}
                    <h3 class="panel-title">
                        {{ name.asset.name }}资产信息
                    </h3>
                {% endfor %}
            </div>



            <!--Chart information-->
            <div class="panel-body " style="position:relative;z-index:2">
                <div class="row">
                 <table id='host_status_list' class="table table-striped table-hover">
                     {% for godcmdb_list in godcmdb_record %}
                     <tr>
                         <td class="text-normal">设备类型</td>
                         <td>{{ godcmdb_list.asset_type }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">设备名</td>
                         <td>{{ godcmdb_list.asset.name }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">资产SN号</td>
                         <td>{{ godcmdb_list.asset.sn|default_if_none:"" }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">生产／测试</td>
                         <td>{{ godcmdb_list.asset.get_production_test_display }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">机柜号</td>
                         <td>{{ godcmdb_list.asset.model }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">机柜位置</td>
                         <td>{{ godcmdb_list.asset.model_position }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">制造商</td>
                         <td>{{ godcmdb_list.asset.manufactory }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">管理IP</td>
                         <td>{{ godcmdb_list.asset.management_ip }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">合同</td>
                         <td>{{ godcmdb_list.asset.contract }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">购买时间</td>
                         <td>{{ godcmdb_list.asset.trade_data }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">过保修期</td>
                         <td>{{ godcmdb_list.asset.expire_date }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">所属业务</td>
                         <td>{{ godcmdb_list.asset.business_unit.name }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">管理员</td>
                         <td>{{ godcmdb_list.asset.admin }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">IDC机房</td>
                         <td>{{ godcmdb_list.asset.idc }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">添加模式</td>
                         <td>{{ godcmdb_list.get_created_by_display }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">CPU信息(核数)</td>
                         <td>{{ godcmdb_list.cpu_info.cpu_core_count }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">内存信息(G)</td>
                         <td>{{ godcmdb_list.mem_info.capacity }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">磁盘信息(G)</td>
                         <td>{{ godcmdb_list.disk_info.capacity }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">内网网卡信息(eth0)</td>
                         <td>{{ godcmdb_list.IPS.ipaddress }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">第二张网卡eth1</td>
                         <td>{{ godcmdb_list.ips1 }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">第三张网卡eth1</td>
                         <td>{{ godcmdb_list.ips2 }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">第四张网卡eth1</td>
                         <td>{{ godcmdb_list.ips3 }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">raid类型</td>
                         <td>{{ godcmdb_list.asset.raid_type }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">系统类型</td>
                         <td>{{ godcmdb_list.os_type }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">创建时间</td>
                         <td>{{ godcmdb_list.create_date|date:'Y-m-d' }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">更新时间</td>
                         <td>{{ godcmdb_list.asset.update_date|date:'Y-m-d' }}</td>
                     </tr>
                     <tr>
                         <td class="text-normal">备注</td>
                         <td>{{ godcmdb_list.asset.memo }}</td>
                     </tr>
                     {% endfor %}
                 </table>
                </div>
            </div>
        <!--===================================================-->
        <!--End network line chart-->

    </div>

  </div>

{% endblock %}