godpig/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('godbody.urls')),
    url(r'^projectpig/', include('projectpig.urls')),
    url(r'^godcmdb/', include('godcmdb.urls')),
    url(r'^godsupport/', include('godsupport.urls')),
    url(r'^admin/', admin.site.urls),
    # url(r'^customers/$',views.customers),
]

projectpig/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from projectpig import views

urlpatterns = [


    url(r'^Projectpig/$', views.Projectpig,name='Projectpig'),
    url(r'^new_article/$', views.new_article,name='new_article'),
    # url(r'^new_article_list/(\d+)/$', views.new_article_list,name='new_article_list'),
    url(r'^new_article_list/$', views.new_article_list,name='new_article_list'),
    url(r'^god_fault/$', views.god_fault,name='god_fault'),
    url(r'^project_fault/$', views.project_fault,name='project_fault'),
    url(r'^bug_fault/$', views.bug_fault,name='bug_fault'),
]

projectpig/models.py
from django.db import models
from django.contrib.auth.models import User
from godbody.models import UserProfile
# Create your models here.

class Projectpig(models.Model):
    project_name = models.CharField(u'项目名',max_length=64)
    person_in_charge = models.ForeignKey(UserProfile,verbose_name='负责人')
    work_content = models.TextField(u'工作内容',)
    open_date = models.DateField(u'开始时间')
    end_choices = (
        (0,'None'),
        (1,u'已完工'),
        (2,u'未完工')
    )
    end_type = models.IntegerField(u'完工状态',choices=end_choices,default=0,blank=True,null=True)
    end_date = models.DateField(u'结束时间',blank=True,null=True)

    def __str__(self):
        return self.work_content

class Project_speed(models.Model):
    article = models.ForeignKey(Projectpig,verbose_name=u"项目跟踪")
    project_track = models.TextField(u'工作进度')
    end_choices = (
        (0,'None'),
        (1,u'已完工'),
        (2,u'未完工')
    )
    end_type = models.IntegerField(u'完工状态',choices=end_choices,default=0,blank=True,null=True)
    name = models.ForeignKey(UserProfile,verbose_name='跟踪人员')
    Completion_date = models.DateField(u'完成时间',blank=True,null=True)
    expect_date = models.DateField(u'预期完成时间',blank=True,null=True)
    memo = models.TextField(u'备注',null=True,blank=True)

    def __str__(self):
        return self.project_track


class god_bug(models.Model):
    god_bug_date = models.DateTimeField(u'故障日期')
    god_bug_choices=(
        (1,u'系统'),
        (2,u'应用'),
        (3,u'网络')
    )
    god_bug_type = models.IntegerField(u'影响类别',choices=god_bug_choices,default=2)
    god_bug_ip = models.CharField(u'故障IP',max_length=32,blank=True,null=True)
    god_bug_phenomenon = models.TextField(u'故障现象')
    god_bug_solve = models.TextField(u'故障解决',blank=True,null=True)
    god_bug_track = models.TextField(u'故障跟踪',blank=True,null=True)
    god_bug_registrant = models.ForeignKey(UserProfile,verbose_name=u"登记人")
    god_bug_remarks = models.CharField(u'备注',max_length=64,blank=True,null=True)

    def __str__(self):
        return self.god_bug_ip

class bug_fault(models.Model):
    bug_code = models.CharField(u'漏洞代码',max_length=32)
    bug_name = models.CharField(u'漏洞名称',max_length=32)
    bug_version = models.CharField(u'漏洞影响版本',max_length=64)
    bug_synopsis = models.TextField(u'漏洞简介')
    bug_harm = models.TextField(u'漏洞危害')
    bug_repair_work_choices = (
        (1,u'已完成'),
        (2,u'未完成')
    )
    bug_repair_work = models.IntegerField(u'修复状况',choices=bug_repair_work_choices,default=1)
    bug_register_time = models.DateField(u"记录时间")
    bug_registrant = models.ForeignKey(UserProfile,verbose_name=u"登记人")
    memo = models.TextField(u'备注',null=True,blank=True)

projectpig/views.py
from django.shortcuts import render
from projectpig import models
from projectpig import form
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from django.contrib.auth import login,logout,authenticate
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

# Create your views here.

#项目登记
def Projectpig(request):
    project_list = models.Projectpig.objects.all()
    return render(request, 'Projectpig/project_list.html', {'project_list':project_list})

#添加项目登记
def new_article(request):
    if request.method == 'GET':
        article_form = form.ArticleModelForm()
        return render(request,'Projectpig/project_add.html',{'article_form':article_form})
    elif request.method == "POST":
        print(request.POST)
        if request.method == 'POST':
            new_article_obj = models.Projectpig(
                project_name = request.POST.get('project_name'),
                person_in_charge = request.POST.get('person_in_charge'),
                work_content = request.POST.get('work_content'),
                open_date = request.POST.get('open_date'),
                end_type = request.POST.get('end_type'),
                end_date = request.POST.get('end_date'),
            )
            new_article_obj.save()
        return HttpResponseRedirect(request.GET.get('next') or '/Projectpig')

        # article_form = form.ArticleModelForm(request.POST)
        # if article_form.is_valid():
        #     article_form.save()
        #     return HttpResponse("ok")
        # else:
        #     return render(request,'Projectpig/project_add.html',{'article_form':article_form})

def new_article_list(request):
    new_article_list_obj = models.Projectpig.objects.all()
    return render(request, 'Projectpig/new_article_list.html', {"new_article_list_obj":new_article_list_obj})

#项目跟踪
def project_fault(request):
    project_fault_obj = models.Project_speed.objects.all()
    return render(request, 'Projectpig/project_fault.html',{"project_fault_obj":project_fault_obj})

#漏洞登记
def bug_fault(request):
    bug_fault_obj = models.bug_fault.objects.all()
    return render(request,'Projectpig/bug_fault.html',{"bug_fault_obj":bug_fault_obj})

# def customers(request):
#     customer_list = models.Projectpig.objects.all()
#
#     paginator = Paginator(customer_list,3)
#     page = request.GET.get('page')
#     try:
#         customer_objs = paginator.page(page)
#     except PageNotAnInteger:
#         customer_objs = paginator.page(1)
#     except EmptyPage:
#         customer_objs = paginator.page(paginator.num_pages)
#
#     return render(request,'Projectpig/project_list.html',{'customer_list':customer_objs})

def god_fault(request):
    god_fault_obj = models.god_bug.objects.all()
    return render(request, 'Projectpig/project_fault_list.html', {"god_fault_obj":god_fault_obj})

templates/Projectpig/bug_fault.html
{% extends 'start/index.html' %}

{% block  page-title %}

    故障登记
{% endblock %}

{% block page-content %}

  <div class="row">
    <div class="col-lg-12">

        <!--Network Line Chart-->
        <!--===================================================-->
        <div class="panel">
            <div class="panel-heading">
                <div class="panel-control">
                    <button id="demo-panel-network-refresh" data-toggle="panel-overlay" data-target="#demo-panel-network" class="btn"><i class="fa fa-rotate-right"></i></button>
                    <div class="btn-group">
                        <button class="dropdown-toggle btn" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-gear"></i></button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#"></a></li>
                            <li><a href="#">添加</a></li>
                            <li><a href="#">跟进</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </div>
                </div>
                <h3 class="panel-title">漏洞登记</h3>
            </div>



            <!--Chart information-->
            <div class="panel-body " style="position:relative;z-index:2">
                <div class="row">
                 <table id='host_status_list' class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <td>漏洞代码</td>
                            <td>漏洞名称</td>
                            <td>漏洞影响版本</td>
                            <td>漏洞简介</td>
                            <td>漏洞危害</td>
                            <td>修复状况</td>
                            <td>记录时间</td>
                            <td>登记人</td>
                            <td>备注</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for bug_fault in bug_fault_obj %}
                        <tr>
                            <td data-type="bug_code">{{ bug_fault.bug_code}}</td>
                            <td data-type="bug_name">{{ bug_fault.bug_name}}</td>
                            <td data-type="bug_version">{{ bug_fault.bug_version|truncatechars:10}}</td>
                            <td data-type="bug_synopsis">{{ bug_fault.bug_synopsis|truncatechars:10 }}</td>
                            <td data-type="bug_harm">{{ bug_fault.bug_harm}}</td>
                            <td data-type="bug_repair_work">{{ bug_fault.get_bug_repair_work_display }}</td>
                            <td data-type="bug_register_time">{{ bug_fault.bug_register_time|date:'Y-m-d' }}</td>
                            <td data-type="bug_registrant">{{ bug_fault.bug_registrant }}</td>
                            <td data-type="memo">{{ bug_fault.memo }}</td>
                        </tr>
                      {% endfor %}
                    </tbody>
                 </table>
                </div>
            </div>
        <!--===================================================-->
        <!--End network line chart-->

    </div>

  </div>

{% endblock %}

templates/Projectpig/new_article_list.html
{% extends 'start/index.html' %}

{% block  page-title %}
{% endblock %}

{% block page-content %}

<div class="row">
        <div class="panel-heading">
            <h3 class="panel-title">项目管理</h3>
        </div>
        <div class="panel-body " style="position:relative;z-index:2">
            <div class="row">
                <form method="post">
                    <dd>{{ new_article_list_obj.project_name }}</dd>



                </form>
            </div>

        </div>
    </div>


{% endblock %}

templates/Projectpig/project_add.html
{% extends 'start/index.html' %}

{% block  page-title %}
    运维开发
{% endblock %}

{% block page-content %}

<div class="row">
        <div class="panel-heading">
            <h3 class="panel-title">添加项目</h3>
        </div>
        <div class="panel-body " style="position:relative;z-index:2">
            <div class="row">
                <form method="post"> {% csrf_token %}
                    {{ article_form }}
                    <input type="submit" class="btn btn-success pull-right" value="确定">
                </form>
            </div>

        </div>
    </div>


{% endblock %}
{% block bottom-js %}
    <script src="/static/plugins/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        CKEDITOR.replace('work_content')

    </script>
{% endblock %}

templates/Projectpig/project_fault.html
{% extends 'start/index.html' %}

{% block  page-title %}

    项目跟踪
{% endblock %}

{% block page-content %}

  <div class="row">
    <div class="col-lg-12">

        <!--Network Line Chart-->
        <!--===================================================-->
        <div class="panel">
            <div class="panel-heading">
                <div class="panel-control">
                    <button id="demo-panel-network-refresh" data-toggle="panel-overlay" data-target="#demo-panel-network" class="btn"><i class="fa fa-rotate-right"></i></button>
                    <div class="btn-group">
                        <button class="dropdown-toggle btn" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-gear"></i></button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#"></a></li>
                            <li><a href="#">添加</a></li>
                            <li><a href="#">跟进</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </div>
                </div>
                <h3 class="panel-title">故障跟踪</h3>
            </div>



            <!--Chart information-->
            <div class="panel-body " style="position:relative;z-index:2">
                <div class="row">
                 <table id='host_status_list' class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <td>项目跟踪</td>
                            <td>工作进度</td>
                            <td>完工状态</td>
                            <td>跟踪人员</td>
                            <td>完成时间</td>
                            <td>预期完成时间</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for god_fault in project_fault_obj %}
                        <tr>
                            <td data-type="article"><a href="#">{{ god_fault.article|truncatechars:10 }}</a></td>
                            <td data-type="project_track">{{ god_fault.project_track}}</td>
                            <td data-type="end_type">{{ god_fault.get_end_type_display}}</td>
                            <td data-type="name">{{ god_fault.name }}</td>
                            <td data-type="Completion_date">{{ god_fault.Completion_date|date:'Y-m-d' }}</td>
                            <td data-type="expect_date">{{ god_fault.expect_date }}</td>
                        </tr>
                      {% endfor %}
                    </tbody>
                 </table>
                </div>
            </div>
        <!--===================================================-->
        <!--End network line chart-->

    </div>

  </div>

{% endblock %}

templates/Projectpig/project_fault_list.html
{% extends 'start/index.html' %}

{% block  page-title %}

    项目管理
{% endblock %}

{% block page-content %}

  <div class="row">
    <div class="col-lg-12">

        <!--Network Line Chart-->
        <!--===================================================-->
        <div class="panel">
            <div class="panel-heading">
                <div class="panel-control">
                    <button id="demo-panel-network-refresh" data-toggle="panel-overlay" data-target="#demo-panel-network" class="btn"><i class="fa fa-rotate-right"></i></button>
                    <div class="btn-group">
                        <button class="dropdown-toggle btn" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-gear"></i></button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#"></a></li>
                            <li><a href="#">添加</a></li>
                            <li><a href="#">跟进</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </div>
                </div>
                <h3 class="panel-title">故障登记</h3>
            </div>



            <!--Chart information-->
            <div class="panel-body " style="position:relative;z-index:2">
                <div class="row">
                 <table id='host_status_list' class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <td>故障日期</td>
                            <td>影响类别</td>
                            <td>故障IP</td>
                            <td>故障现象</td>
                            <td>故障解决</td>
                            <td>故障跟踪</td>
                            <td>登记人</td>
                            <td>备注</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for god_fault in god_fault_obj %}
                        <tr>
                            <td data-type="god_bug_date"><a href="#">{{ god_fault.god_bug_date|date:'Y-m-d h:m:s' }}</a></td>
                            <td data-type="god_bug_type">{{ god_fault.get_god_bug_type_display }}</td>
                            <td data-type="god_bug_ip">{{ god_fault.god_bug_ip }}</td>
                            <td data-type="god_bug_phenomenon">{{ god_fault.god_bug_phenomenon|truncatechars:10 }}</td>
                            <td data-type="god_bug_solve">{{ god_fault.god_bug_solve|truncatechars:10 }}</td>
                            <td data-type="god_bug_track">{{ god_fault.god_bug_track|truncatechars:10 }}</td>
                            <td data-type="god_bug_registrant">{{ god_fault.god_bug_registrant }}</td>
                            <td data-type="god_bug_remarks">{{ god_fault.god_bug_remarks }}</td>

                        </tr>
                      {% endfor %}
                    </tbody>
                 </table>
                </div>
            </div>
        <!--===================================================-->
        <!--End network line chart-->

    </div>

  </div>

{% endblock %}

templates/Projectpig/project_list.html
{% extends 'start/index.html' %}

{% block  page-title %}

    项目管理
{% endblock %}

{% block page-content %}

  <div class="row">
    <div class="col-lg-12">

        <!--Network Line Chart-->
        <!--===================================================-->
        <div class="panel">
            <div class="panel-heading">
                <div class="panel-control">
                    <button id="demo-panel-network-refresh" data-toggle="panel-overlay" data-target="#demo-panel-network" class="btn"><i class="fa fa-rotate-right"></i></button>
                    <div class="btn-group">
                        <button class="dropdown-toggle btn" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-gear"></i></button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#"></a></li>
                            <li><a href="{% url 'new_article' %}">添加</a></li>
                            <li><a href="#">跟进</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </div>
                </div>
                <h3 class="panel-title">运维开发</h3>
            </div>



            <!--Chart information-->
            <div class="panel-body " style="position:relative;z-index:2">
                <div class="row">
                 <table id='host_status_list' class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <td>项目名称</td>
                            <td>负责人</td>
                            <td>工作内容</td>
                            <td>开始时间</td>
                            <td>是否完工</td>
                            <td>结束时间</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for project in project_list %}
                        <tr>
                            <td data-type="project_name"><a href="{% url 'new_article_list' %}">{{ project.project_name }}</a></td>
                            <td data-type="person_in_charge">{{ project.person_in_charge }}</td>
                            <td data-type="work_content">{{ project.work_content|truncatechars:30 }}</td>

                            <td data-type="open_date">{{ project.open_date|date:"Y-m-d" }}</td>
                            <td data-type="end_type">{{ project.get_end_type_display }}</td>
                            <td data-type="end_date">{{ project.end_date }}</td>
                        </tr>
                      {% endfor %}
                    </tbody>
                 </table>
                </div>
            </div>
        <!--===================================================-->
        <!--End network line chart-->
        </div>

    </div>
  </div>

{% endblock %}